name: Unity Request License

on:
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .alf
        uses: game-ci/unity-builder@v4
        continue-on-error: true
        with:
          unityVersion: 2022.3.22f1
          projectPath: unity
          skipActivation: true
          customParameters: -createManualActivationFile -quit -nographics
      - name: Upload .alf
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unity-license-alf
          path: |
            *.alf
            **/*.alf
          if-no-files-found: error
