name: Unity Request License

on:
  workflow_dispatch: {}

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.22f1
          projectPath: unity
          requestManualActivationFile: true
      - uses: actions/upload-artifact@v4
        with:
          name: Unity-license-alf
          path: |
            *.alf
            **/*.alf
          if-no-files-found: error
